title: Shamanth B C
logo: /assets/img/sam.jpg
description:
  <p align="center">

  <a href="https://https://linkedin.com/in/shamanth-b-c-920390123/">LinkedIn</a> |
  <a href="https://https://github.com/shmanth">GitHub</a>
  
  <br>   
  I'm working on AI and Machine learning Course.   
    Worked in Zerodha for a year.
  <br>
  </p>
theme: jekyll-theme-minimal
